### ISSUE TITLE
Choose color function

### ISSUE THREAD

**Issue by luismasterbranch** [Yisaaaa/CCPRGG2L_DrawingApp#1]
You will be using JColorChooser here. [Brocode](https://www.youtube.com/watch?v=zEw8xObSWNA) has one video talking about it. You will be mainly working in the `Sidebar class`.

In the `Sidebar class` there is an `actionPerformed` method already. So your main task is basically adding a condition to check if the button -- stored in a variable called `source` -- clicked is the `JButton colorBtn`. After that you will use the `setColorSelected` to store the color chosen with JColorChooser.

**Comment by ArjTheProgrammer** [comment]
copy senior developer 😊😊😊
